/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package pa1;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2022-02-18")
public enum SchedulingPolicy implements org.apache.thrift.TEnum {
  RANDOM(0),
  BALANCING(1);

  private final int value;

  private SchedulingPolicy(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static SchedulingPolicy findByValue(int value) { 
    switch (value) {
      case 0:
        return RANDOM;
      case 1:
        return BALANCING;
      default:
        return null;
    }
  }
}
