/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package pa1;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2022-02-18")
public class NodeReceipt implements org.apache.thrift.TBase<NodeReceipt, NodeReceipt._Fields>, java.io.Serializable, Cloneable, Comparable<NodeReceipt> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NodeReceipt");

  private static final org.apache.thrift.protocol.TField DIRECTORY_FIELD_DESC = new org.apache.thrift.protocol.TField("directory", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField FILE_FIELD_DESC = new org.apache.thrift.protocol.TField("file", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new NodeReceiptStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new NodeReceiptTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String directory; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String file; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DIRECTORY((short)1, "directory"),
    FILE((short)2, "file");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DIRECTORY
          return DIRECTORY;
        case 2: // FILE
          return FILE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DIRECTORY, new org.apache.thrift.meta_data.FieldMetaData("directory", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FILE, new org.apache.thrift.meta_data.FieldMetaData("file", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NodeReceipt.class, metaDataMap);
  }

  public NodeReceipt() {
  }

  public NodeReceipt(
    java.lang.String directory,
    java.lang.String file)
  {
    this();
    this.directory = directory;
    this.file = file;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NodeReceipt(NodeReceipt other) {
    if (other.isSetDirectory()) {
      this.directory = other.directory;
    }
    if (other.isSetFile()) {
      this.file = other.file;
    }
  }

  public NodeReceipt deepCopy() {
    return new NodeReceipt(this);
  }

  @Override
  public void clear() {
    this.directory = null;
    this.file = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDirectory() {
    return this.directory;
  }

  public NodeReceipt setDirectory(@org.apache.thrift.annotation.Nullable java.lang.String directory) {
    this.directory = directory;
    return this;
  }

  public void unsetDirectory() {
    this.directory = null;
  }

  /** Returns true if field directory is set (has been assigned a value) and false otherwise */
  public boolean isSetDirectory() {
    return this.directory != null;
  }

  public void setDirectoryIsSet(boolean value) {
    if (!value) {
      this.directory = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getFile() {
    return this.file;
  }

  public NodeReceipt setFile(@org.apache.thrift.annotation.Nullable java.lang.String file) {
    this.file = file;
    return this;
  }

  public void unsetFile() {
    this.file = null;
  }

  /** Returns true if field file is set (has been assigned a value) and false otherwise */
  public boolean isSetFile() {
    return this.file != null;
  }

  public void setFileIsSet(boolean value) {
    if (!value) {
      this.file = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case DIRECTORY:
      if (value == null) {
        unsetDirectory();
      } else {
        setDirectory((java.lang.String)value);
      }
      break;

    case FILE:
      if (value == null) {
        unsetFile();
      } else {
        setFile((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DIRECTORY:
      return getDirectory();

    case FILE:
      return getFile();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DIRECTORY:
      return isSetDirectory();
    case FILE:
      return isSetFile();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof NodeReceipt)
      return this.equals((NodeReceipt)that);
    return false;
  }

  public boolean equals(NodeReceipt that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_directory = true && this.isSetDirectory();
    boolean that_present_directory = true && that.isSetDirectory();
    if (this_present_directory || that_present_directory) {
      if (!(this_present_directory && that_present_directory))
        return false;
      if (!this.directory.equals(that.directory))
        return false;
    }

    boolean this_present_file = true && this.isSetFile();
    boolean that_present_file = true && that.isSetFile();
    if (this_present_file || that_present_file) {
      if (!(this_present_file && that_present_file))
        return false;
      if (!this.file.equals(that.file))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetDirectory()) ? 131071 : 524287);
    if (isSetDirectory())
      hashCode = hashCode * 8191 + directory.hashCode();

    hashCode = hashCode * 8191 + ((isSetFile()) ? 131071 : 524287);
    if (isSetFile())
      hashCode = hashCode * 8191 + file.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(NodeReceipt other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDirectory()).compareTo(other.isSetDirectory());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDirectory()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.directory, other.directory);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFile()).compareTo(other.isSetFile());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFile()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.file, other.file);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("NodeReceipt(");
    boolean first = true;

    sb.append("directory:");
    if (this.directory == null) {
      sb.append("null");
    } else {
      sb.append(this.directory);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("file:");
    if (this.file == null) {
      sb.append("null");
    } else {
      sb.append(this.file);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NodeReceiptStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NodeReceiptStandardScheme getScheme() {
      return new NodeReceiptStandardScheme();
    }
  }

  private static class NodeReceiptStandardScheme extends org.apache.thrift.scheme.StandardScheme<NodeReceipt> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NodeReceipt struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DIRECTORY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.directory = iprot.readString();
              struct.setDirectoryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FILE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.file = iprot.readString();
              struct.setFileIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NodeReceipt struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.directory != null) {
        oprot.writeFieldBegin(DIRECTORY_FIELD_DESC);
        oprot.writeString(struct.directory);
        oprot.writeFieldEnd();
      }
      if (struct.file != null) {
        oprot.writeFieldBegin(FILE_FIELD_DESC);
        oprot.writeString(struct.file);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NodeReceiptTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NodeReceiptTupleScheme getScheme() {
      return new NodeReceiptTupleScheme();
    }
  }

  private static class NodeReceiptTupleScheme extends org.apache.thrift.scheme.TupleScheme<NodeReceipt> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NodeReceipt struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDirectory()) {
        optionals.set(0);
      }
      if (struct.isSetFile()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetDirectory()) {
        oprot.writeString(struct.directory);
      }
      if (struct.isSetFile()) {
        oprot.writeString(struct.file);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NodeReceipt struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.directory = iprot.readString();
        struct.setDirectoryIsSet(true);
      }
      if (incoming.get(1)) {
        struct.file = iprot.readString();
        struct.setFileIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

